### ISSUE TITLE
panic when list image that be pulled by digest.

### ISSUE THREAD

**Issue by yanxuean** [kubernetes-incubator/cri-tools#155]
panic: runtime error: index out of range

I can fix it.

Log is below.
```
root@ubuntu:/home/cloud/go/src/github.com/kubernetes-incubator/cri-containerd# crictl pull docker.io/library/busybox@sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.io/library/busybox@sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642,},Auth:nil,SandboxConfig:nil,} 
DEBU[0002] PullImageResponse: &PullImageResponse{ImageRef:sha256:c30178c5239f2937c21c261b0365efcda25be4921ccb95acd63beeeb78786f27,} 
Image is update to date for sha256:c30178c5239f2937c21c261b0365efcda25be4921ccb95acd63beeeb78786f27
root@ubuntu:/home/cloud/go/src/github.com/kubernetes-incubator/cri-containerd# crictl images
DEBU[0000] ListImagesRequest: &ListImagesRequest{Filter:&ImageFilter{Image:&ImageSpec{Image:,},},} 
DEBU[0000] ListImagesResponse: &ListImagesResponse{Images:[&Image{Id:sha256:c30178c5239f2937c21c261b0365efcda25be4921ccb95acd63beeeb78786f27,RepoTags:[],RepoDigests:[docker.io/library/busybox@sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642],Size_:701277,Uid:nil,Username:,}],} 
panic: runtime error: index out of range

goroutine 1 [running]:
main.glob..func10(0xc4200e4780, 0x0, 0xc4200e4780)
	/home/cloud/go/src/github.com/kubernetes-incubator/cri-tools/cmd/crictl/image.go:135 +0x5b1
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.HandleAction(0x1375cc0, 0x15c3870, 0xc4200e4780, 0xc42006f400, 0x0)
	/home/cloud/go/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.Command.Run(0x155c234, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x156176e, 0xb, 0x0, ...)
	/home/cloud/go/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.(*App).Run(0xc420087ba0, 0xc42000c1e0, 0x2, 0x2, 0x0, 0x0)
	/home/cloud/go/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/home/cloud/go/src/github.com/kubernetes-incubator/cri-tools/cmd/crictl/main.go:195 +0xaaf
```

**Comment by yanxuean** [comment]
@feiskyer @Random-Liu 
PTAL

**Comment by feiskyer** [comment]
@yanxuean would you like to file a PR for fixing this?

**Comment by yanxuean** [comment]
@feiskyer 
Yes,  I'm fixing it. :)

**Comment by Random-Liu** [comment]
I also see this today.
