### ISSUE TITLE
crictl images fails with panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by adelton** [kubernetes-incubator/cri-tools#265]
With CRI-O build from its master (712f3b8cf14cbbac298f3ccc020677ac2a65fa75) and `cri-tools` built from its master (a6dd109ef238be53ab9a7a5c4642f8a1d4ba1bd6), running

```
# crictl pull registry.fedoraproject.org/fedora:27
```

passed but

```
# crictl images
```

fails with

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.glob..func13(0xc4200738c0, 0x0, 0xc4200738c0)
	/root/cri-tools/_output/src/github.com/kubernetes-incubator/cri-tools/cmd/crictl/image.go:155 +0x1002
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.HandleAction(0xca43a0, 0xe233f0, 0xc4200738c0, 0xc420055000, 0x0)
	/root/cri-tools/_output/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.Command.Run(0xdc4743, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdc9024, 0xb, 0x0, ...)
	/root/cri-tools/_output/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/command.go:210 +0xa95
github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli.(*App).Run(0xc420061a00, 0xc42000c060, 0x2, 0x2, 0x0, 0x0)
	/root/cri-tools/_output/src/github.com/kubernetes-incubator/cri-tools/vendor/github.com/urfave/cli/app.go:255 +0x6f8
main.main()
	/root/cri-tools/_output/src/github.com/kubernetes-incubator/cri-tools/cmd/crictl/main.go:218 +0xc71
```

Running

```
# crictl images --no-trunc
```

shows

```
IMAGE                               TAG                 IMAGE ID                                                           SIZE
<none>                              <none>                                                                                 0B
registry.fedoraproject.org/fedora   27                  99b71991af6eef73e85e3a657641cf2447929f37fff1f9570d525a6ef485a4a8   246MB
```

**Comment by adelton** [comment]
I forgot -- the `crictl` was configured with

```
echo 'runtime-endpoint: unix:///var/run/crio/crio.sock' > /etc/crictl.yaml
```

and this is on Fedora 27 host.

**Comment by mrunalp** [comment]
cc: @runcom

**Comment by runcom** [comment]
Will look, thanks for the report!

**Comment by mrunalp** [comment]
@adelton One of the PRs that went into cri-o master broke this. This isn't a cri-tools issue.

**Comment by feiskyer** [comment]
Even in this case, crictl shouldn't panic itself. Let me file a PR to fix this.

/assign

**Comment by adelton** [comment]
Should this somehow be reported to CRI-O as well?
